### ISSUE TITLE
Dependency is using mdns@master, which breaks Slackware build

### ISSUE THREAD

**Issue by rcombs** [benvanik/node-airplay#3]
http://pastie.org/5026845 <-- Details here. mdns's current release is fine on the same machine.

**Comment by benvanik** [comment]
Ack! I started playing with writing an mDNS client (that just works with AirPlay devices) in pure JS - this dependency is a pain! If you have a patch that fixes it I'll take it, otherwise I'll just try to actually do some work and get the better solution implemented.

**Comment by benvanik** [comment]
Pushed your changes - thanks!
